function hRD = plugin_rd()
% Reference design definition for DE10-Nano SoC
% For DeepLearningProcessor workflow

% Copyright 2025

% Create reference design object
hRD = hdlcoder.ReferenceDesign('SynthesisTool', 'Altera QUARTUS II');

hRD.ReferenceDesignName = 'DE10 Nano Soc Reference Design';
hRD.BoardName = 'Terasic DE10-Nano SoC';

% Tool version (Quartus Prime version used)
hRD.SupportedToolVersion = {'21.1'};  % Update based on your install

%% Add custom design files
% add custom Qsys design
hRD.addCustomQsysDesign( ...
    'CustomQsysPrjFile', 'system_soc.qsys');

% Add IP from HDL Verifier support package
msg = message('hdlcommon:plugin:IPRepositoryHDLVerifierAlteraNotFound').getString;
hRD.addIPRepository( ...
    'IPListFunction','hdlverifier.fpga.quartus.iplist', ...
    'NotExistMessage', msg);

% Add AXI4-Stream to AXI4-Master DDR Access IP
hRD.addIPRepository( ...
	'IPListFunction','hdlcoder.fpga.quartus.hdlcoder_axis2axim_iplist', ...
	'NotExistMessage', 'AXI4-Stream to AXI4 Master IP not found.');

% Add AXI4-Stream gasket IP
hRD.addIPRepository(...
    'IPListFunction', 'mathworks.fpga.quartus.hdlcoder_axisgasket_iplist',...
    'NotExistMessage', 'MathWorks IP repository not found');

% Add ADI DMA IP
hRD.addIPRepository(...
    'IPListFunction', 'adi.fpga.quartus.hdlcoder_dma_iplist',...
    'NotExistMessage', 'Analog Devices IP repository not found');

%% Add clock interface
hRD.addClockInterface( ...
    'ClockConnection',     'pll_0.outclk0', ...
    'ResetConnection',     'hps_0.h2f_reset',...
    'DefaultFrequencyMHz', 50,...
    'MinFrequencyMHz',     5,...
    'MaxFrequencyMHz',     500,...
    'ClockModuleInstance', 'pll_0',...
    'ClockNumber',         0);

%% Add AXI4 Interfcaes

% add AXI4 slave interfaces
hRD.addAXI4SlaveInterface( ...
    'InterfaceConnection', 'AXI_Manager_0.axm_m0', ...
    'BaseAddress',         '0x00000000', ...
    'InterfaceType',       'AXI4', ...
    'IDWidth',             13);

% add AXI4 Master interface
hRD.addAXI4MasterInterface(...
    'InterfaceID',      'AXI4 Master Activation Data', ...
    'ReadSupport',      true, ...
    'WriteSupport',     true, ...
    'MaxDataWidth',     512, ...
    'AddrWidth',        32, ...
    'DefaultReadBaseAddr', hex2dec('40000000'), ...
    'DefaultWriteBaseAddr', hex2dec('40000000'), ...
    'InterfaceConnection', 'hps_0.f2h_sdram0_data', ...
    'Prevent4KBoundaryCrossing', false ...
    );

% add AXI4 Master interface
hRD.addAXI4MasterInterface(...
    'InterfaceID',      'AXI4 Master Weight Data', ...
    'ReadSupport',      true, ...
    'WriteSupport',     true, ...
    'MaxDataWidth',     512, ...
    'AddrWidth',        32, ...
    'DefaultReadBaseAddr', hex2dec('40000000'), ...
    'DefaultWriteBaseAddr', hex2dec('40000000'), ...
    'InterfaceConnection', 'hps_0.f2h_sdram0_data', ...
    'Prevent4KBoundaryCrossing', false ...
    );

% add AXI4 Master interface
hRD.addAXI4MasterInterface(...
    'InterfaceID',      'AXI4 Master Debug', ...
    'ReadSupport',      true, ...
    'WriteSupport',     true, ...
    'MaxDataWidth',     512, ...
    'AddrWidth',        32, ...
    'DefaultReadBaseAddr', hex2dec('40000000'), ...
    'DefaultWriteBaseAddr', hex2dec('40000000'), ...
    'InterfaceConnection', 'hps_0.f2h_sdram0_data', ...
    'Prevent4KBoundaryCrossing', false ...
    );

hRD.GenerateSplitBitstream = true;

% Deep learning specific properties
hRD.registerDeepLearningTargetInterface("JTAG");
hRD.registerDeepLearningTargetInterface("Ethernet");
hRD.registerDeepLearningMemoryAddressSpace(0x40000000, 0x40000000); % 1GB

% Resource utilization information
hRD.ResourcesUsed.LogicElements = 50000; % 110000;
hRD.ResourcesUsed.DSP = 50; % 112;
hRD.ResourcesUsed.RAM = 26.5;

end
